### ISSUE TITLE
Clear procedure for adding a new SoC

### ISSUE THREAD

**Issue by coleramos425** [ROCm/omniperf#180]
**Describe the suggestion**
Develop and document a clear procedure for adding a new SoC

**Justification**
With the changes in place to encapsulate all SoC unique properties in a class, adding a new SoC will be easier for maintainers. If we document this procedure it will also make things easier for contributors when they want to add an SoC that they're particularly interested in.

**Implementation**
Add relevant comments in source code as well as update documentation so the procedure is clear to external users

_Originally posted by @coleramos425 in https://github.com/AMDResearch/omniperf/discussions/153#discussioncomment-6806981_

**Comment by ppanchad-amd** [comment]
Closing since task is completed.
