### ISSUE TITLE
Can there be an easier way to list launch params for a given kernel dispatch?

### ISSUE THREAD

**Issue by gsitaram** [ROCm/omniperf#191]
**Is your feature request related to a problem? Please describe.**
Today, we have to do something like this to get launch parameters for a given dispatch.
```
omniperf analyze –p <workload_path> --dispatch 1 --metric 7.1.0 7.1.1 7.1.2​
```
First of all, the user has to know what these metric ids are. For this, they have to run `omniperf analyze` once to get the entire output, then scan the output to figure that out. Then, the above command has to be used. 

**Describe the solution you'd like**
I wonder if a small set of easy to use options may be helpful. For example, for this particular case, something like this may be easy to remember and use:
```
omniperf analyze -p <workload_path> --dispatch 1 --show-launch-params
```

**Describe alternatives you've considered**
I understand that such requests deviate from the "keep it simple" philosophy that I subscribe to, but still wanted to submit this request for consideration by the omniperf team.

**Comment by feizheng10** [comment]
First, "For this, they have to run omniperf analyze once to get the entire output",  the option --list-metrics is supposed to do that.
Second, we also suppose to provide corresponding IP block names(or metric names) for filtering.
Ether way, I'd say, for now, depending the workload, each team need to create their template for filtering...

**Comment by ppanchad-amd** [comment]
@gsitaram Closing ticket as there is no plan to support the request. Thanks!
