### ISSUE TITLE
'Issue loading top kernels. Check pmc_kernel_top.csv' when using --no-roof on MI200

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [ROCm/omniperf#313]
**Describe the bug**
```
omniperf profile -n test --no-roof -- ./whatever
omniperf analyze -p workloads/test/MI200
$ omniperf analyze -p workloads/stream/MI200/

  ___                  _                  __ 
 / _ \ _ __ ___  _ __ (_)_ __   ___ _ __ / _|
| | | | '_ ` _ \| '_ \| | '_ \ / _ \ '__| |_ 
| |_| | | | | | | | | | | |_) |  __/ |  |  _|
 \___/|_| |_| |_|_| |_|_| .__/ \___|_|  |_|  
                        |_|                  

Analysis mode = cli
[analysis] deriving Omniperf metrics...
Issue loading top kernels. Check pmc_kernel_top.csv
```

Digging a bit, it appears we're emitting this from here:

https://github.com/AMDResearch/omniperf/blob/bfef4200993f0110f45753f8f9c4a7810b83c6ff/src/utils/parser.py#L926

when the roofline csv doesn't exist.  At the very least we shouldn't _always_ say it's top_kernels.csv or w/e, and say "no roofline detected".  Arguably, this shouldn't be a warning at all as --no-roof is a valid use-case?

**Comment by ppanchad-amd** [comment]
@skyreflectedinmirrors Issue is fixed. Closing ticket. Thanks!
