### ISSUE TITLE
Non-deterministic ordering of pmc_perf_*.txt file (sometimes???)

### ISSUE THREAD

**Issue by skyreflectedinmirrors** [ROCm/omniperf#332]
https://github.com/ROCm/omniperf/blob/59254a50463a8f3fe44c6b1f06610edf53e2c30c/src/omniperf_profile/profiler_base.py#L90

RE: our internal debug, we noticed counters from a `pmc:` line in a file, _occasionally_ get split over multiple runs in pmc_perf_<#>.txt.  This results in nonsensical values sometimes, due to-to-run variation.

Need to debug how this could happen.

Seems like some sort of non-deterministic ordering in a python API / pandas / etc.

**Comment by ppanchad-amd** [comment]
@skyreflectedinmirrors Issue is fixed. Closing ticket. Thanks!
