### ISSUE TITLE
Where can i find the meaning of some metrics from omniperf?

### ISSUE THREAD

**Issue by xinji1** [ROCm/omniperf#338]
**Describe your question**
Just wondering if there are some explanations on what some mertics means (like nvidia compute). For example, i'd like to know `MFMA`, `VALU` and so on, while there're no documents i could refer to. I appreciate it if you could provide some documents in the README.md.
![image](https://github.com/ROCm/omniperf/assets/147899933/4be5e7ff-9f69-4650-a1a3-8fc3bc1d53c1)

Also,  i wanna know if there're some metrics we can regard as the counterparts of `Compute Throughput`/ `Memory Throughput` in nsight compute.

![image](https://github.com/ROCm/omniperf/assets/147899933/78f0a450-3aa3-4b29-b03b-2e23f0927d40)

**Additional context**
Add any other context or screenshots about the question here.

**Comment by Xi-Meng** [comment]
@xinji1 Excuse me, do you solve this problem or find some documents? I am also very confused the meaning of the metrics.

**Comment by ppanchad-amd** [comment]
Hi @xinji1. Internal ticket has been created to assist with your request. Thanks!

**Comment by zichguan-amd** [comment]
Hi @xinji1, the system speed of light section in the documentation mentioned above (https://rocm.github.io/omniperf/performance_model.html#system-speed-of-light) contains all the metrics that we currently support. There is no direct equivalent to `Compute Throughput/ Memory Throughput`, but we do have all the bandwidth and utilization metrics separately. Hope this clears things up.

**Comment by JensenFire** [comment]
Thanks you guys. I think there's no further problem.
