### ISSUE TITLE
Kernel filtering with Omniperf profile in MI300X

### ISSUE THREAD

**Issue by Jacob0226** [ROCm/omniperf#339]
**Describe the bug**
In the issue [325](https://github.com/ROCm/omniperf/issues/325), it seems that you can use rocprofv1 to choose the kernels that are being profiled. But on the MI300X machine with gfx942, gfx942 only works with rocprofv2. gfx942 is not enabled in rocprofv1. When I use rocprofv2 and `-k` in omniperf, the kernels are not filtered. omniperf profile all of the kernels.

**Development Environment:**
 - Linux Distribution: Ubuntu 20.04.6 LTS (Focal Fossa)
 - Omniperf Version: 2.0.0-RC1 (release), Git revision:     4fc30eb
 - GPU: MI300X
 - ROCM: 6.1.0

**To Reproduce**
1. Download sample code[ vcopy.cpp](https://github.com/ROCm/omniperf/blob/main/sample/vcopy.cpp)
```
hipcc vcopy.cpp -o vcopy
export ROCPROF=/opt/rocm-6.1.0-13394/bin/rocprof
omniperf profile -n vcopy_kernel -k vecCopy -- ./vcopy -n 1048576 -b 256
```

**Expected behavior**
It pops out an error:

> ERROR gfx942 is not enabled in rocprofv1. Available profilers include: ['rocprofv2']

I have tried with rocprofv2, it would profile all kernels and that is not what I want.

**Comment by coleramos425** [comment]
Hi @Jacob0226. Apologies for the delay in response. When using Omniperf on MI300 we need to specify the rocprofv2 profiler to Omniperf, otherwise it will attempt to use rocprofv1.

Please set `export ROCPROF=rocprofv2`. Your new steps would look something like
```
hipcc vcopy.cpp -o vcopy
export ROCPROF=/opt/rocm-6.1.0-13394/bin/rocprofv2
omniperf profile -n vcopy_kernel -k vecCopy -- ./vcopy -n 1048576 -b 256
```

**Comment by coleramos425** [comment]
> ERROR gfx942 is not enabled in rocprofv1. Available profilers include: ['rocprofv2']

Right. This error is to be expected since rocprofv1 does not have compatibility with MI300. This seems to be the same issue as reported in #325 which we found is a bug in rocprofv2, not Omniperf. If you feel this is not a duplicate issue, please re-open.
