### ISSUE TITLE
MI300 omniperf analyze mode: per_kernel normalization results in error

### ISSUE THREAD

**Issue by amnamasood-amd** [ROCm/omniperf#349]
**Describe the bug**
After profiling, omniperf analyze with -n per_kernel results in the following error:
ERROR: [analysis] 'float' object has no attribute 'empty'

**Development Environment:**
Ubuntu 22.04
Omniperf version: 2.0.0 (dev)
Git revision:     2f00dfb
GPU: MI300A A1, MI300X A1

**To Reproduce**
For BabelStream:
1. Run 'omniperf profile -n streamtest2 -- ./hip-stream -s $((825*1024*1024))'
2. Run 'omniperf analyze -p workloads/streamtest2/MI300X_A1/ -k 0 -n per_kernel'

This error is consistent across different apps, even the vcopy application in omniperf/samples

**Comment by coleramos425** [comment]
Hi @amnamasood-amd. I applied a patch for your issue to the `dev` branch this afternoon. Could you please pull and confirm this fixes your problem? Thanks!

**Comment by amnamasood-amd** [comment]
Hi @coleramos425 I checked and I am able to get the correct CLI output. Thank you!
