### ISSUE TITLE
gfx908 doesn't support roofline plot

### ISSUE THREAD

**Issue by aymane-eljerari** [ROCm/omniperf#385]
**Is your feature request related to a problem? Please describe.**
I am unable to generate roofline plots using omniperf on MI100 (gfx908)

**Describe the solution you'd like**
Being able to generate the roofline plots automatically when profiling using omniperf.

**Describe alternatives you've considered**
So far, I only have access to speed of light values.

**Additional context**
```
root@febc8da47e3f:~/git/rocm-llm-profile# ./omniperf_profile.sh 
  DEBUG ROC Profiler: /opt/rocm-6.0.0/bin/rocprof
  DEBUG Execution mode = profile

  ___                  _                  __ 
 / _ \ _ __ ___  _ __ (_)_ __   ___ _ __ / _|
| | | | '_ ` _ \| '_ \| | '_ \ / _ \ '__| |_ 
| |_| | | | | | | | | | | |_) |  __/ |  |  _|
 \___/|_| |_| |_|_| |_|_| .__/ \___|_|  |_|  
                        |_|                  

  DEBUG [profiling] perform SoC profiling setup for gfx908
  ERROR gfx908 does not support roofline analysis
```

**Comment by coleramos425** [comment]
@aymane-eljerari MI100 (gfx908) hardware doesn't support matrix fused multiply-add (MFMA) instructions. MFMA is a critical part of Omniperf's roofline methodology, thus to maintain this consistency, we do not plan to add support for this generation of hardware.
